 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var moment = require('moment');
var app = express();

const port = process.env.PORT || 3000;

app.use((req, res) => {
  const timestamp = req.originalUrl.substring(1, req.originalUrl.length - 1);
  let date;
  if (timestamp.indexOf('%20') === -1) {
    date = new Date(timestamp * 10000);
  } else {
    date = new Date(decodeURI(timestamp));
  }
  
  res.json({
    unix: date.getTime() / 1000,
    natural: moment(date).format('MMMM DD, YYYY') === 'Invalid date' ? null : moment(date).format('MMMM DD, YYYY'),
  });
})

app.listen(port, function () {
  console.log(`Node.js listening on port ${port}`);
});

